const datainfo = [
  {
    img: "Hotels/The Westin.jpg",
    name: "The Westin",
    category: "Luxury Hotels",
    location:
      "The Westin Kolkata, CBD/2, International Financial Hub(CBD), Newtown, Kolkata, West Bengal 700156 ",
    price: 3000,
    range: 3000,
    rating: "4star",
  },
  {
    img: "Hotels/Kolkata Hayat.jpg",
    name: "Hyatt Regency",
    category: "Luxury Hotels",
    location:
      "JA-1, JA Block, Sector III, Bidhannagar, Kolkata, West Bengal 700106",
    price: 6500,
    range: 7000,
    rating: "4star",
  },
  {
    img: "Hotels/itc-sonar.png",
    name: "ITC Sonar",
    category: "Luxury Hotels",
    location: "1, JBS Haldane Ave, Tangra, Kolkata, West Bengal 700046",
    price: 9250,
    range: 10000,
    rating: "5star",
  },
  {
    img: "Hotels/elite_apartment.jpg",
    name: "The Elite Apartment Hotel",
    category: "Luxury Hotels",
    location:
      "441, Hussainpur Main Rd, Madurdaha, Hussainpur, Kolkata, West Bengal 700107",
    price: 784,
    range: 1000,
    rating: "3star",
  },
  {
    img: "Hotels/Hotel_rituivy.jpg",
    name: "Hotel RituIvy",
    category: "Luxury Hotels",
    location:
      "The Gateway Hotel Em Bypass, Sector C, East Kolkata Township, 215, near GST Bhavan and, Shantipally, Kasba, Kolkata, West Bengal 700107",
    price: 2800,
    range: 3000,
    rating: "4star",
  },
  {
    img: "Hotels/Kolkata_JW Marriott.jpg",
    name: "JW Marriott",
    category: "Luxury Hotels",
    location: "4A, JBS Haldane Ave, Tangra, Kolkata, West Bengal 700105",
    price: 15930,
    range: 16000,
    rating: "4star",
  },
  {
    img: "Hotels/peerless_inn.jpg",
    name: "The Peerless Inn",
    category: "Luxury Hotels",
    location: "12, Jawaharlal Nehru Rd, Esplanade, Dharmatala, Taltala, Kolkata, West Bengal 700013",
    price: 6159,
    range: 7000,
    rating: "4star",
  },
  {
    img: "Hotels/Novotel.jpg",
    name: "Novotel",
    category: "Luxury Hotels",
    location: "Cf 11, CB Block(Newtown), Action Area 1C, Newtown, Kolkata, New Town, West Bengal 700156",
    price: 5151,
    range: 7000,
    rating: "4star",
  },

  {
    img: "Hotels/city_central.jpg",
    name: "City Central",
    category: "Hostels",
    location: "57 Mahatma Gandhi Road 4th floor, near chitranjan college, 700009 Kolkata, India",
    price: 900,
    range: 1000,
    rating: "3star",
  },
  {
    img: "Hotels/Fabhotel_mega.jpg",
    name: "FabHotel Mega Grand",
    category: "Hostels",
    location: "401 Lake Town Road, Block B, Kolkata, 700089 Kolkata, India",
    price: 1950,
    range: 2000,
    rating: "3star",
  },
  {
    img: "Hotels/GutenTag_Hostel.jpg",
    name: "Guten Tag",
    category: "Hostels",
    location: "BJ-339, BJ Block, Sector 2, Salt Lake, 700091 Kolkata, India",
    price: 555,
    range: 1000,
    rating: "4star",
  },
  {
    img: "Hotels/OfficeBeat.jpg",
    name: "Offbeat CCU Bunkers",
    category: "Hostels",
    location: "36/F, Topsia Rd., Topsia, West Bengal, 700039 Kolkata, India",
    price: 650,
    range: 1000,
    rating: "3star",
  },
  {
    img: "Hotels/lynq-cico.jpg",
    name: "LYNQ Cico",
    category: "Boutique Hotels",
    location: "14A, Burdwan Rd, near Alipore, Alipore, Kolkata, West Bengal 700027",
    price: 2500,
    range: 3000,
    rating: "3star",
  },
  {
    img: "Hotels/altair.jpg",
    name: "AltAir",
    category: "Boutique Hotels",
    location: "Ambuja Neotia EcoCentre, 4, 19, Street No. 13, EM Block, Sector V, Bidhannagar, Kolkata, West Bengal 700091",
    price: 5500,
    range: 7000,
    rating: "5star",
  },
  {
    img: "Hotels/kingston-boutique-hotel.jpg",
    name: "Kingston",
    category: "Boutique Hotels",
    location: "JC76+273, Jessore Rd, Amarpalli, South Dumdum, West Bengal 700055",
    price: 1594,
    range: 3000,
    rating: "4star",
  },
  {
    img: "Hotels/poisse.jpg",
    name: "Poiisse",
    category: "Boutique Hotels",
    location: " 45B/B, Canal S Rd, near Byepass, Metropolitan Co-Operative Housing Society Limited, Ltd, Dhaba, West Bengal 700105",
    price: 2401,
    range: 3000,
    rating: "star",
  },
  {
    img: "Hotels/Vedicvillage.jpg",
    name: "Village Spa Resort",
    category: "Resort Hotels",
    location: "Shikharpur P.O, Bagu, Newtown, Sikharpur, West Bengal 700135",
    price: 4075,
    range: 5000,
    rating: "4star",
  },
  {
    img: "Hotels/aquatica-resort.jpg",
    name: "Aquatica Water Theme Park and Resort",
    category: "Resort Hotels",
    location: "Kolkata Railway Station13.9 kms away ; Netaji Subhash Chandra Bose International Airport13.5 kms away",
    price: 2549,
    range: 3000,
    rating: "3star",
  },
  {
    img: "Hotels/Ekante_cottage.jpg",
    name: "Ekante Cottage",
    category: "Resort Hotels",
    location: "HFX8+GCW, Rina Walk Way, Eco-Tourism Park, Jatragachhi, Deshbandhu Nagar, Newtown, Kolkata, West Bengal 700156",
    price: 5468,
    range: 7000,
    rating: "4star",
  },
  {
    img: "Hotels/lbdresortandhotels.jpg",
    name: "LBD Resorts & Hotels",
    category: "Resort Hotels",
    location: "31/1, NC Chowdhury Rd, Bosepukur, Kasba, Kolkata, West Bengal 700042",
    price: 3360,
    range: 5000,
    rating: "3star",
  },
  {
    img: "Hotels/raajkutir.jpg",
    name: "Raajkutir",
    category: "Business Hotels",
    location: "89C, Narkeldanga Main Rd, Kadapara, Phool Bagan, Kankurgachi, Kolkata, West Bengal 700054",
    price: 5761,
    range: 7000,
    rating: "4star",
  },
  {
    img: "Hotels/lemon-tree-premier-new.jpg",
    name: "Lemon Tree Premier",
    category: "Business Hotels",
    location: "Premises No. 30-1111, BG-9, Service Rd, Newtown, West Bengal 700156",
    price: 3202,
    range: 5000,
    rating: "4star",
  },
  {
    img: "Hotels/Vivanta.jpg",
    name: "Vivanta",
    category: "Business Hotels",
    location: " 1930, Rash Behari Ave, Sector G, East Kolkata Twp, Kolkata, West Bengal 700107",
    price: 5600,
    range: 7000,
    rating: "5star",
  },
  {
    img: "Hotels/TajKolkata.jpg",
    name: "Taj Bengal",
    category: "Business Hotels",
    location: "34-B, Belvedere Rd, Alipore, Kolkata, West Bengal 700027",
    price: 9735,
    range: 10000,
    rating: "5star",
  },
  {
    img: "Hotels/ethnotel.jpg",
    name: "Ethnotel",
    category: "Airport Hotels",
    location: "71, Airport 2½ Gate, 1, Jessore Rd, Dum Dum, North Dumdum, West Bengal 700081",
    price: 4256,
    range: 5000,
    rating: "4star",
  },
  {
    img: "Hotels/Holiday_Inn.jpg",
    name: "Holiday Inn",
    category: "Airport Hotels",
    location: "Biswa Bangla Sarani, near City Centre 2, Dash Drone, Newtown, Kolkata, West Bengal 700136",
    price: 4253,
    range: 5000,
    rating: "5star",
  },{
    img: "Hotels/Hotel_air_view.jpg",
    name: "Hotel Air View",
    category: "Airport Hotels",
    location: "NO 2.5, 53, Jessore Rd, International Airport, Manikpur, Rajbari, Dum Dum, Kolkata, North Dumdum, West Bengal 700081",
    price: 1168,
    range: 3000,
    rating: "3star",
  },
  {
    img: "Hotels/Airport_city_hotel.jpg",
    name: "Airport City Hotel",
    category: "Airport Hotels",
    location: "259, Jessore Rd, Khalisha Kota, Dum Dum, North Dumdum, West Bengal 700081•033 2513 3131",
    price: 3245,
    range: 5000,
    rating: "3star",
  },
  {
    img: "Hotels/zonebythepark.jpg",
    name: "Zone by the Park",
    category: "Budget Hotels",
    location: "DG /02/1 -39, 11 (न्युटाउन, Action Area I, Newtown, New Town, West Bengal 700156",
    price: 2489,
    range: 3000,
    rating: "3star",
  },{
    img: "Hotels/Hotelsenes.jpg",
    name: "Senses Hotel",
    category: "Budget Hotels",
    location: "DN-26, Street Number 11, DN Block, Sector V, Bidhannagar, Kolkata, West Bengal 700091",
    price: 2741,
    range: 3000,
    rating: "4star",
  },{
    img: "Hotels/hotel-de-sovrani.jpg",
    name: "De Sovrani",
    category: "Budget Hotels",
    location: "DD-21, DD Block, Sector 1, Bidhannagar, Kolkata, West Bengal 700064",
    price: 3118,
    range: 5000,
    rating: "3star",
  },{
    img: "Hotels/innra_hotel.jpg",
    name: "Innra Guest Hourse",
    category: "Budget Hotels",
    location: "124 1, Bepin Behari Ganguly St, Lebutala, Bowbazar, Kolkata, West Bengal 700012",
    price: 1232,
    range: 3000,
    rating: "3star",
  },
];
export default datainfo;